qtwebengine: add missing include
Taken from:
https://raw.githubusercontent.com/clemensg/ptxdist/master/patches/qt-everywhere-opensource-src-5.6.1-1/0103-qtwebengine-add-missing-include.patch

Without this building fails new newer glibc with:

.../touch_evdev_debug_buffer.h:37:15: error: field 'device_name_' has
incomplete type 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}'

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>